name: Test Shrek with QEMU

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: sudo apt install gcc-arm-none-eabi qemu-system-arm device-tree-compiler
    - name: Run test suite (virt)
      run: timeout -s 9 20s make virt-test
    - name: Run test suite (vexpress)
      run: timeout -s 9 20s make vexpress-test
    - name: Run test suite (pi)
      run: timeout -s 9 20s make pi-test
