---
name: Test Shrek with QEMU

on: [push, pull_request]

jobs:
  build:
    env:
      EXTRA_CXXFLAGS: -Werror
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update repositories
        run: sudo apt update
      - name: Install toolchain
        run: >-
          sudo apt install gcc-arm-none-eabi qemu-system-arm
          device-tree-compiler
      - name: Run test suite (virt)
        run: make clean && timeout -s 9 20s make -j virt-test
      - name: Run test suite (vexpress)
        run: make clean && timeout -s 9 20s make -j vexpress-test
      - name: Run test suite (pi)
        run: make clean && timeout -s 9 20s make -j pi-test
      - name: Install linters
        run: pip install cpplint yamllint; sudo gem install mdl
      - name: Lint
        run: make lint
      - name: Lint CI files
        run: yamllint $(find .github -name '*.yml' -o -name '*.yaml')
